name: QuantumExitScan
version: '1.0'
main: owleaf.quantumexitscan.QuantumExitScan
api-version: '1.20'
commands:
  q:
    description: Comando principal de QuantumExitScan
    usage: |
      /q reload - Recarga la configuración
      /q radio <valor> - Cambia el radio de detección
      /q life <valor> - Cambia el umbral de vida baja
      /q reset - Restablece configuración
      /q list - Lista jugadores autorizados
      /q warnings <id> - Detalles de advertencia
permissions:
  quantumexit.admin:
    description: Acceso total a los comandos
    default: op